#
# Module manifest for module 'PSSDPAPI'
#
# Generated by: Michal Gajda
#
# Generated on: 2021-12-21
#

@{

    # Script module or binary module file associated with this manifest
    RootModule = 'PSSDPAPI.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.2.7'

    # ID used to uniquely identify this module
    GUID = '48a0d8c8-9858-4289-ad71-58acc91e3868'

    # Author of this module
    Author = 'Michal Gajda'

    # Company or vendor of this module
    CompanyName = ''

    # Copyright statement for this module
    Copyright = '(c) 2026 Michal Gajda. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Modul PowerShell do obslugi API ServiceDesk Plus.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    PowerShellHostVersion = ''

    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = ''

    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules = ''

    # Functions to export from this module
    FunctionsToExport = @(
        'Close-SDPRequest'
        'Close-SDPRequestTask'
        'ConvertTo-Hashtable'
        'Get-SDPCategory'
        'Get-SDPItem'
        'Get-SDPRequest'
        'Get-SDPRequestNote'
        'Get-SDPRequestResolution'
        'Get-SDPRequestTask'
        'Get-SDPRequestWorklog'
        'Get-SDPSubcategory'
        'Get-SDPTechnician'
        'Get-SDPUser'
        'Invoke-SDPAPIEntity'
        'Move-SDPRequestToTrash'
        'New-SDPCategory'
        'New-SDPItem'
        'New-SDPRequest'
        'New-SDPRequestNote'
        'New-SDPRequestResolution'
        'New-SDPRequestTask'
        'New-SDPRequestTaskWorklog'
        'New-SDPRequestWorklog'
        'New-SDPSubcategory'
        'New-SDPTechnician'
        'New-SDPUser'
        'Remove-SDPCategory'
        'Remove-SDPItem'
        'Remove-SDPRequest'
        'Remove-SDPRequestNote'
        'Remove-SDPRequestTask'
        'Remove-SDPSubcategory'
        'Remove-SDPTechnician'
        'Remove-SDPUser'
        'Restore-SDPRequestFromTrash'
        'Set-SDPApiConnection'
        'Set-SDPCategory'
        'Set-SDPItem'
        'Set-SDPRequest'
        'Set-SDPRequestNote'
        'Set-SDPRequestTask'
        'Set-SDPRequestTaskOwner'
        'Set-SDPRequestTechnician'
        'Set-SDPRequestWorklog'
        'Set-SDPSubcategory'
        'Set-SDPTechnician'
        'Set-SDPTechnicianAsUser'
        'Set-SDPUser'
        'Set-SDPUserAsTechnician'
    )

    # Cmdlets to export from this module
    CmdletsToExport = ''

    # Variables to export from this module
    VariablesToExport = ''

    # Aliases to export from this module
    AliasesToExport = ''

    # List of all modules packaged with this module
    ModuleList = @()

    # List of all files packaged with this module
    FileList = @(
        'Admin\Category\Get-SDPCategory.ps1'
        'Admin\Category\New-SDPCategory.ps1'
        'Admin\Category\Remove-SDPCategory.ps1'
        'Admin\Category\Set-SDPCategory.ps1'
        'Admin\Item\Get-SDPItem.ps1'
        'Admin\Item\New-SDPItem.ps1'
        'Admin\Item\Remove-SDPItem.ps1'
        'Admin\Item\Set-SDPItem.ps1'
        'Admin\Subcategory\Get-SDPSubcategory.ps1'
        'Admin\Subcategory\New-SDPSubcategory.ps1'
        'Admin\Subcategory\Remove-SDPSubcategory.ps1'
        'Admin\Subcategory\Set-SDPSubcategory.ps1'
        'Admin\Technician\Get-SDPTechnician.ps1'
        'Admin\Technician\New-SDPTechnician.ps1'
        'Admin\Technician\Remove-SDPTechnician.ps1'
        'Admin\Technician\Set-SDPTechnician.ps1'
        'Admin\Technician\Set-SDPTechnicianAsUser.ps1'
        'Admin\User\Get-SDPUser.ps1'
        'Admin\User\New-SDPUser.ps1'
        'Admin\User\Remove-SDPUser.ps1'
        'Admin\User\Set-SDPUser.ps1'
        'Admin\User\Set-SDPUserAsTechnician.ps1'
        'Helpers\ConvertTo-Hashtable.ps1'
        'Helpers\Invoke-SDPAPIEntity.ps1'
        'Helpers\Set-SDPApiConnection.ps1'
        'Request\Close-SDPRequest.ps1'
        'Request\Get-SDPRequest.ps1'
        'Request\Move-SDPRequestToTrash.ps1'
        'Request\New-SDPRequest.ps1'
        'Request\Note\Get-SDPRequestNote.ps1'
        'Request\Note\New-SDPRequestNote.ps1'
        'Request\Note\Remove-SDPRequestNote.ps1'
        'Request\Note\Set-SDPRequestNote.ps1'
        'Request\Remove-SDPRequest.ps1'
        'Request\Resolution\Get-SDPRequestResolution.ps1'
        'Request\Resolution\New-SDPRequestResolution.ps1'
        'Request\Restore-SDPRequestFromTrash.ps1'
        'Request\Set-SDPRequest.ps1'
        'Request\Set-SDPRequestTechnician.ps1'
        'Request\Task\Close-SDPRequestTask.ps1'
        'Request\Task\Get-SDPRequestTask.ps1'
        'Request\Task\New-SDPRequestTask.ps1'
        'Request\Task\Remove-SDPRequestTask.ps1'
        'Request\Task\Set-SDPRequestTask.ps1'
        'Request\Task\Set-SDPRequestTaskOwner.ps1'
        'Request\Task\Worklog\New-SDPRequestTaskWorklog.ps1'
        'Request\Worklog\Get-SDPRequestWorklog.ps1'
        'Request\Worklog\New-SDPRequestWorklog.ps1'
        'Request\Worklog\Set-SDPRequestWorklog.ps1'
    )

    # Private data to pass to the module specified in ModuleToProcess
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/mgajda83/PSSDPAPI/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/mgajda83/PSSDPAPI'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
